### ISSUE TITLE
MATLAB code?

### ISSUE THREAD

**Issue by junpenglao** [neurodata/r-mgc#22]
Hi there,
I am wondering where can I find the Matlab code? According to the paper, it seems the library is available in both R and Matlab?

**Comment by ebridge2** [comment]
https://github.com/neurodata-papers/MGC/tree/master/Code/MGC let me know if this works for you!

**Comment by junpenglao** [comment]
Thanks!

**Comment by jovo** [comment]
@ebridge2 maybe we should mention this in the readme?

**Comment by cshen6** [comment]
yep a cross-reference will be good.

**Comment by ebridge2** [comment]
readme updated to have a link to matlab code @cshen6 @jovo
