### ISSUE TITLE
add k-sample test functionality to R, and 20 simulations for ind / k-sample into the demo/test 

### ISSUE THREAD

**Issue by cshen6** [neurodata/r-mgc#4]
@youjin1207 

Once you sent me your R code (ideally before weekend, as long as they work!), 
I will write a few more lines to make them consistent with my matlab counterpart; 
then we will have @ebridge2 integrating them properly.

**Comment by youjin1207** [comment]
@cshen6 @ebridge2  I just uploaded two R codes which only have *basic* functions. Especially for KSData, I have no idea how to clear up. `list(X, Y)` in KSData.R is a first input of `KSTestMGC(dat = list(X,Y), dist = 'Euclidean')` function, for example.

https://github.com/youjin1207/KST/blob/master/Code/KSTestMGC.R

**Comment by cshen6** [comment]
thanks. It looks just fine to me.

I will take them and add one more script for running; then eric will help
us get them in order.
