### ISSUE TITLE
optimalScale not defaulting to global scale when variables have a linear relationship

### ISSUE THREAD

**Issue by MaxKerney** [neurodata/r-mgc#45]
I'm not sure whether this is a bug or a new feature, but when doing a test of two variables that are perfectly linearly correlated MGC returns long vectors of seemingly every scale for optimalScale$x and optimalScale$y, e.g.:

```
glimpse(output)
List of 6
 $ stat        : num 1
 $ localCorr   : num [1:112, 1:112] 1 0.81 0.697 0.565 0.528 ...
 $ optimalScale:List of 2
  ..$ x: num [1:1516] 78 79 80 81 82 77 78 79 80 81 ...
  ..$ y: num [1:1516] 45 45 45 45 45 46 46 46 46 46 ...
 $ option      : chr "mgc"
 $ p.localCorr : num [1:112, 1:112] 0.000999 0.000999 0.000999 0.000999 0.000999 ...
 $ p.value     : num 0.000999
```
I thought that when variables are linearly correlated MGC should default to the single global scale. That is how it used to behave, so, as I said, I don't know whether this is a new bug or a new design decision?

**Comment by ebridge2** [comment]
A reproducible example would be helpful for figuring out what's up; I reordered the output spec when making the last CRAN push so probably just accidentally deleted a line :(

My attempt to reproduce from what you sent seems to have been unsuccessful:

```
> x <- matrix(1:10, ncol=1); y <- matrix(1:10, ncol=1)
> res <- mgc.test(matrix(x, ncol=1), matrix(y, ncol=1), nperm=20)  # 20 permutations test; typically should be run with >1000 permutations
> res$optimalScale
$x
[1] 10

$y
[1] 10
```
which uses the whatever's on CRAN at the moment which I believe is from a few months ago. Further the other elements of the result appear accurate as well.

**Comment by MaxKerney** [comment]
Sure thing, here you go. Apologies that it goes a bit around the houses creating a tibble, selecting data, and creating distance matrices, etc., but I was trying to mimic my real code.

```
library(mgc)
library(cluster)
library(tidyverse)
  
mt_data <- as_tibble(mtcars) %>%
select(mpg) %>%
mutate(mpg2 = 1/mpg)
  
var1_dist <- data.matrix(daisy(mt_data[, "mpg"]))   
var2_dist <- data.matrix(daisy(mt_data[, "mpg2"]))
  
result <- mgc.test(X = var1_dist, Y = var2_dist, is.dist.X = TRUE, is.dist.Y = TRUE, nperm = 100)
  
result$optimalScale

$x
[1]  3 21 21

$y
[1]  3 19 22
```
In the process of creating the reprex I discovered that it might have something to do with rounding, because if the data are rounded it seems to work:

```
mt_data <- as_tibble(mtcars) %>%
select(mpg) %>%
mutate(mpg2 = 1/mpg) %>%
mutate(across(everything(), ~ round(., digits = 2)))
  
var1_dist_test <- data.matrix(daisy(mt_data[, "mpg"]))   
var2_dist_test <- data.matrix(daisy(mt_data[, "mpg2"]))
  
result <- mgc.test(X = var1_dist_test, Y = var2_dist_test, is.dist.X = TRUE, is.dist.Y = TRUE, nperm = 100)
  
result$optimalScale

$x
[1] 23

$y
[1] 5
```

**Comment by ebridge2** [comment]
Hi @MaxKerney, so 2 things:
1) The inverse is a textbook example of a non-linearity, not a linearity. A "perfectly linear" relationship occurs in a straight line; if you were to say plot x vs -1/x you would get a downward sloping curve. For example, if (x, y) are such that y = mx + b for any (m, b) then (x, y) is a linear pair; if no such (m, b) exists satisfying this then (x,y) are non-linearly related. Plugging in y = -1/x it will become clear rather quickly that no such (m, b) exist.

2) When I run this example using the corresponding python package:
```
require(reticulate)
use_virtualenv("~/.virtualenvs/hyppo/", required=TRUE)
py_config()
mgc <- import("hyppo.independence")

# ksample testing wrapper
mgc.test <- function(X, Y, method="MGC", is.dist=TRUE, nrep=1000L, ...) {
  X=X
  mgc <- py_suppress_warnings(import("hyppo.independence")[[method]]())
  
  Y=Y
  res <- py_suppress_warnings(mgc$test(X, Y, reps=nrep))
  names(res) <- c("statistic", "pvalue")
  return(res)
}
res_py=mgc.hyppo(X, Y, nrep=100L)
res_R=mgc.test(X, Y, is.dist.X=TRUE, is.dist.Y=TRUE, nperm=100L)
```
And I check through the corresponding python optimal scales, ie:
```
> res_py[[3]]$mgc_map[res_R$optimalScale$x[2], res_R$optimalScale$y[2]]
0.9971306
```
The values of the optimal scales in the list that R says are 1 but the corresponding python code says are less than 1 are all extremely close to 1, so not quite sure what the source of the discrepancy is between the two but it is somewhere in the way that correlations are computed between the two packages which I'll see if I can uncover this weekend, but appears to be quite small in magnitude. Assuming the R code is accurate though I believe returning a list of optimal scales for ties is the sensible thing to do in this case since none are objectively better than the other(s).

**Comment by jovo** [comment]
@cshen6 what do you think?

**Comment by MaxKerney** [comment]
Ah, sorry, I forgot to add that my data are log-transformed, which is why I was seeing a linear relationship:

```
mt_data <- as_tibble(mtcars) %>%
  select(mpg) %>% 
  mutate(mpg2 = 1/mpg) %>% 
  mutate(across(everything(), log))
```
![MGC-reprex](https://user-images.githubusercontent.com/36264475/94123521-cb989c00-fe4b-11ea-959b-822d96f2c389.png)

Again, it may have something to do with rounding, because in this example it works when the data are log-transformed:

```
result$optimalScale

$x
[1] 25

$y
[1] 25
```
One difference seems to be that the transformation operation rounds the values:

```
# Untransformed
head(mt_data)

# A tibble: 6 x 2
    mpg   mpg2
  <dbl>  <dbl>
1  21   0.0476
2  21   0.0476
3  22.8 0.0439
4  21.4 0.0467
5  18.7 0.0535
6  18.1 0.0552

# Transformed
head(mt_data)

# A tibble: 6 x 2
    mpg  mpg2
  <dbl> <dbl>
1  3.04 -3.04
2  3.04 -3.04
3  3.13 -3.13
4  3.06 -3.06
5  2.93 -2.93
6  2.90 -2.90
```
As I said, it seemed to work fine before, so it might be something that was only introduced recently.

**Comment by ebridge2** [comment]
@MaxKerney AH I've discovered the issue! your array has 25 unique entries, not 32; I think this always would (and should) report `25x25` as the optimal scale. Perhaps we could more elegantly point out when this arises? As I agree it wasn't totally clear what was going on. Perhaps a warning that says "Warning: your first entry has p unique entries!" "Warning! your second entry has q unique entries!" "Optimal scales will be less than p and q respectively.". What do you guys think? @jovo @sampan501 to weigh in as well would be great.

**Comment by MaxKerney** [comment]
That makes sense, but I don't think it explains the issue of returning multiple optimal scales. Here's a sample of my real data because the mtcars data didn't seem to replicate the issue very well: [data.zip](https://github.com/neurodata/r-mgc/files/5282890/data.zip). You can see that even after transformation so that the relationship is ostensibly linear multiple optimal scales are still returned:

```
library(mgc)
library(cluster)
library(tidyverse)

data <- read_csv("data.csv")

data <-  mutate(data, across(everything(), log))

var1_dist <- data.matrix(daisy(data[, "var1"]))   
var2_dist <- data.matrix(daisy(data[, "var2"]))

result <- mgc.test(X = var1_dist, Y = var2_dist, is.dist.X = TRUE, is.dist.Y = TRUE, nperm = 100)

result$optimalScale

$x
 [1] 16 17 18 14 15 16 17 18 14 15 16 17 18 14 15 16 17 18 11 12 13 15 16 17 18 11 12 13 14 16 17 18 10 11 12 13 14 15 17 10 11 12 13 14 15 16 10 11 12 13 14 15

$y
 [1] 10 10 10 11 11 11 11 11 12 12 12 12 12 13 13 13 13 13 14 14 14 14 14 14 14 15 15 15 15 15 15 15 16 16 16 16 16 16 16 17 17 17 17 17 17 17 18 18 18 18 18 18
```

**Comment by ebridge2** [comment]
@MaxKerney you have tons of duplicate entries in that example as well, leading to the scale issue... try to not pass identical items and I believe your problem will be solved.
